# Simple workflow for deploying static content to GitHub Pages
name: Deploy Elusive Software
permissions:
  contents: read

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
    paths: [ gkwebNew/**, gkwebNew.Tests/**, apiObjects/** ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "elusive"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: [ self-hosted ]
    name: Deploy Elusive Software
    outputs: 
      build: ${{ steps.buildid.outputs.formattedTime }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate Build Number
        id: buildid
        uses: josStorer/get-current-time@v2.1.2
        with:
          utcOffset: "00:00"
          format: YYYY.MM.DD-HH.mm
      - name: Run Tests
        run: |
          dotnet test gkwebNew.Tests/gkwebNew.Tests.csproj  --configuration Release --logger "console;verbosity=minimal" > C:/deployment-stage/gkes-tests-${{ steps.buildid.outputs.formattedTime }}.md 
      - name: List all changed files
        run: |
          Set-Content -Path C:/deployment-stage/gkes-${{ steps.buildid.outputs.formattedTime }}.txt -Value ""
          Add-Content -Path C:/deployment-stage/gkes-${{ steps.buildid.outputs.formattedTime }}.txt -Value "Publish Results for Elusive Software"
          Add-Content -Path C:/deployment-stage/gkes-${{ steps.buildid.outputs.formattedTime }}.txt -Value ""
          Add-Content -Path C:/deployment-stage/gkes-${{ steps.buildid.outputs.formattedTime }}.txt -Value "Build Number - ${{ steps.buildid.outputs.formattedTime }}"
          Add-Content -Path C:/deployment-stage/gkes-${{ steps.buildid.outputs.formattedTime }}.txt -Value "---------------------------------"
          Add-Content -Path C:/deployment-stage/gkes-${{ steps.buildid.outputs.formattedTime }}.txt -Value ""
          Add-Content -Path C:/deployment-stage/gkes-${{ steps.buildid.outputs.formattedTime }}.txt -Value "Commit Item Messages:"
          Add-Content -Path C:/deployment-stage/gkes-${{ steps.buildid.outputs.formattedTime }}.txt -Value "---------------------------------"
          Add-Content -Path C:/deployment-stage/gkes-${{ steps.buildid.outputs.formattedTime }}.txt -Value $(git log --format=%B -n 1 HEAD)
          Add-Content -Path C:/deployment-stage/gkes-${{ steps.buildid.outputs.formattedTime }}.txt -Value ""
          Add-Content -Path C:/deployment-stage/gkes-${{ steps.buildid.outputs.formattedTime }}.txt -Value "Changed Files"
          Add-Content -Path C:/deployment-stage/gkes-${{ steps.buildid.outputs.formattedTime }}.txt -Value "---------------------------------"
          Add-Content -Path C:/deployment-stage/gkes-${{ steps.buildid.outputs.formattedTime }}.txt -Value $(git diff --name-status ORIG_HEAD..)
          Add-Content -Path C:/deployment-stage/gkes-${{ steps.buildid.outputs.formattedTime }}.txt -Value ""
          Add-Content -Path C:/deployment-stage/gkes-${{ steps.buildid.outputs.formattedTime }}.txt -Value "Test Results:"
          Add-Content -Path C:/deployment-stage/gkes-${{ steps.buildid.outputs.formattedTime }}.txt -Value "---------------------------------"
          Add-Content -Path C:/deployment-stage/gkes-${{ steps.buildid.outputs.formattedTime }}.txt -Value (Get-Content -Path C:/deployment-stage/gkes-tests-${{ steps.buildid.outputs.formattedTime }}.md)
      - name: Create Backup
        run: |
          New-Item -ItemType "directory" -Path "C:/deployment-stage/gkes/${{ steps.buildid.outputs.formattedTime }}/" -Force
          Copy-Item C:/www-root/glorykidd.com/* -Destination C:/deployment-stage/gkes/${{ steps.buildid.outputs.formattedTime }}/ -Recurse
          Compress-Archive -Path "C:/deployment-stage/gkes/${{ steps.buildid.outputs.formattedTime }}/*" -Update -DestinationPath C:/backups/gkes-${{ steps.buildid.outputs.formattedTime }}.zip -CompressionLevel "Fastest"
          Remove-Item -Path C:/deployment-stage/gkes/${{ steps.buildid.outputs.formattedTime }} -Recurse
      - name: Deploy New Code
        run: |
          cd gkwebNew.Server
          dotnet build
          dotnet publish -c Release -o C:/www-root/glorykidd.com
      - name: Email Notification 
        run: |
          cd  D:/it-tools/mailer 
          ./SesMailer.exe --to "David Nuckolls <david.nuckolls@glorykidd.com>" --subject "Elusive Software Build ${{ steps.buildid.outputs.formattedTime }}" --body C:/deployment-stage/gkes-${{ steps.buildid.outputs.formattedTime }}.txt --format text  --from-display-name "Elusive Software" 
